### ISSUE TITLE
Migrate Jellyfin Media

### ISSUE THREAD

**Issue by chrispro-21** [Chris-Pro-Hosting/Tickets#9]
A new server that @Redditor247 and I have been developing is almost ready for development. However, I want to make sure that its storage is ready and can handle all of the incoming media that its going to need

### Hardware
- [ ] Rebuild storage array with 1TB disks
- [ ] Migrate over to ZFS if possible because that raid card is slow as balls
- [ ] Install a network switch down in the basement

### Software
- [ ] migrate over to Nginx and cert-manager

### Todo still:
- [ ] Migrate media over from Truenas to local storage
- [ ] setup rate limited backup from old server to new server
- [ ] setup authentik
- [ ] Import all plugins and metadata
- [ ] Send logs to Wazuh
  - [ ] tell docker to use syslog

**Comment by chrispro-21** [comment]
I still need to build the new array

**Comment by chrispro-21** [comment]
Working on setting up array but this is in backlog
